Output docs/eol-date.gif

Set TypingSpeed 75ms
Set FontSize 18
Set Width 1280
Set Height 800

Type "Welcome to eol-date!"
Sleep 1

Space

Type "A tool to query the endoflife.date API."
Sleep 1

Ctrl+A
Ctrl+K

Type "eol-date django"
Sleep 500ms
Enter
Sleep 5s

Hide
Type "clear"
Enter
Show

Type "eol-date django --all"
Sleep 500ms
Enter
Sleep 5s

Hide
Type "clear"
Enter
Show

Type "eol-date post"
Sleep 500ms
Enter
Sleep 2s
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Enter
Sleep 5s
